language: python
sudo: false
dist: xenial
install:
  - pip install tox
script:
  - tox
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-django111-sqlite
    - python: 3.6
      env: TOXENV=py36-django20-sqlite
    - python: 3.6
      env: TOXENV=py36-django21-sqlite
    - python: 3.6
      env: TOXENV=py36-django22-sqlite
    - python: 3.6
      env: TOXENV=py36-django30-sqlite
    - python: 3.7
      env: TOXENV=py37-django22-sqlite
    - python: 3.7
      env: TOXENV=py37-django30-sqlite
    - python: 3.8
      env: TOXENV=coverage
    - python: 3.8
      env: TOXENV=style
